name: Release Charts

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    uses: trowaflo/github-actions/.github/workflows/release-helm.yml@5fb2cae3cedca812c197e489685f810eef7f286d # v1.2.0
    permissions:
      contents: write
      pages: write
    with:
      harden_runner_egress_policy: audit
      enable_release: true
      release_charts_dirs: "charts/library charts/apps"
