name: Release Charts

on:
  push:
    branches:
      - main

permissions: read-all

jobs:
  release:
    uses: trowaflo/github-actions/.github/workflows/release-helm.yml@d51fc48891c455f85a902e3d23f8ac7a52ef273e # v1.1.0
    permissions:
      contents: write
      pages: write
    with:
      harden_runner_egress_policy: audit
      enable_release: true
      release_charts_dirs: "charts/library charts/apps"
