name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  security:
    uses: trowaflo/github-actions/.github/workflows/security.yml@8358d28b9b77208a15f1fa3536c03baca0d21650 # v2.1.0
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    with:
      harden_runner_egress_policy: audit

  lint:
    uses: trowaflo/github-actions/.github/workflows/lint.yml@8358d28b9b77208a15f1fa3536c03baca0d21650 # v2.1.0
    permissions:
      contents: read
      security-events: write
    with:
      harden_runner_egress_policy: audit
      enable_yamllint: true
