name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  security:
    uses: trowaflo/github-actions/.github/workflows/security.yml@5fb2cae3cedca812c197e489685f810eef7f286d # v1.2.0
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    with:
      harden_runner_egress_policy: audit

  lint:
    uses: trowaflo/github-actions/.github/workflows/lint.yml@5fb2cae3cedca812c197e489685f810eef7f286d # v1.2.0
    permissions:
      contents: read
      security-events: write
    with:
      harden_runner_egress_policy: audit
      enable_yamllint: true
