name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

permissions: read-all

jobs:
  security:
    uses: trowaflo/github-actions/.github/workflows/security.yml@d51fc48891c455f85a902e3d23f8ac7a52ef273e # v1.1.0
    permissions:
      contents: read
      pull-requests: write
      security-events: write
    with:
      harden_runner_egress_policy: audit

  lint:
    uses: trowaflo/github-actions/.github/workflows/lint.yml@d51fc48891c455f85a902e3d23f8ac7a52ef273e # v1.1.0
    permissions:
      contents: read
      security-events: write
    with:
      harden_runner_egress_policy: audit
      enable_yamllint: true
