name: Helm PR Cleanup

on:
  pull_request:
    types: [closed]

permissions: read-all

jobs:
  cleanup:
    uses: trowaflo/github-actions/.github/workflows/ci-helm-cleanup.yml@5fb2cae3cedca812c197e489685f810eef7f286d # v1.2.0
    permissions:
      contents: write
      pull-requests: write
    with:
      harden_runner_egress_policy: audit
