name: Helm CI

on:
  pull_request:
    paths:
      - "charts/**"

permissions: read-all

jobs:
  helm-ci:
    uses: trowaflo/github-actions/.github/workflows/ci-helm.yml@d51fc48891c455f85a902e3d23f8ac7a52ef273e # v1.1.0
    permissions:
      contents: write
      pull-requests: write
    with:
      harden_runner_egress_policy: audit
      enable_lint: true
      enable_bump: true
