name: Helm CI

on:
  pull_request:
    paths:
      - "charts/**"

permissions: read-all

jobs:
  helm-ci:
    uses: trowaflo/github-actions/.github/workflows/ci-helm.yml@5fb2cae3cedca812c197e489685f810eef7f286d # v1.2.0
    permissions:
      contents: write
      pull-requests: write
    with:
      harden_runner_egress_policy: audit
      enable_lint: true
      enable_bump: true
